//! Tauri IPC commands for local AI chat via llama.cpp/Ollama.
//!
//! Provides streaming chat functionality through Tauri's event system.
//! All user messages are pseudonymized before being sent to the LLM,
//! and responses are de-pseudonymized before being returned to the frontend.

use serde::{Deserialize, Serialize};
use tauri::{command, AppHandle, Manager, Runtime};
use tokio::sync::Mutex;
use std::sync::Arc;

use crate::domain::entities::{SigiloLevel, ChatMessage, ChatRole};
use crate::domain::errors::AppError;
use crate::infra::sidecar::SidecarManager;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// Payload sent from the frontend to start a chat completion.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatRequest {
    /// Unique conversation identifier (UUIDv4 generated by the frontend).
    pub conversation_id: String,
    /// The user's message content (plain text, may contain PII).
    pub message: String,
    /// Previous messages in the conversation for context.
    #[serde(default)]
    pub history: Vec<ChatMessageDto>,
    /// Sigilo (confidentiality) level of the current processo context.
    #[serde(default = "default_sigilo")]
    pub sigilo_level: u8,
    /// Optional: model override (e.g. "llama3", "mistral").
    pub model: Option<String>,
    /// Optional: system prompt override for specialised legal tasks.
    pub system_prompt: Option<String>,
    /// Optional: temperature override (0.0 – 1.0).
    pub temperature: Option<f64>,
    /// Optional: max tokens for the response.
    pub max_tokens: Option<u32>,
}

fn default_sigilo() -> u8 {
    1
}

/// DTO for a single chat message exchanged over IPC.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatMessageDto {
    pub role: String,   // "system" | "user" | "assistant"
    pub content: String,
}

/// Streamed chunk emitted to the frontend via Tauri events.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatStreamChunk {
    pub conversation_id: String,
    /// Incremental text delta.
    pub delta: String,
    /// Whether this is the final chunk.
    pub done: bool,
    /// Cumulative token count (if available from the backend).
    pub token_count: Option<u32>,
}

/// Final response returned by the non-streaming command variant.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatResponse {
    pub conversation_id: String,
    pub content: String,
    pub model: String,
    pub token_count: u32,
}

/// Lightweight status response.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AiStatusResponse {
    pub available: bool,
    pub backend: String, // "ollama" | "llama_cpp" | "none"
    pub models: Vec<String>,
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Default system prompt for legal assistant context.
const DEFAULT_SYSTEM_PROMPT: &str = r#"Você é um assistente jurídico especializado no direito brasileiro. 
Responda de forma precisa, citando legislação, jurisprudência e doutrina quando pertinente. 
Nunca invente informações. Se não souber, diga que não sabe. 
Todas as informações pessoais foram substituídas por placeholders — não tente adivinhar dados reais."#;

/// Build the messages payload to send to the Python sidecar.
fn build_sidecar_payload(
    request: &ChatRequest,
) -> serde_json::Value {
    let system_prompt = request
        .system_prompt
        .as_deref()
        .unwrap_or(DEFAULT_SYSTEM_PROMPT);

    let mut messages = Vec::with_capacity(request.history.len() + 2);

    // System message
    messages.push(serde_json::json!({
        "role": "system",
        "content": system_prompt
    }));

    // History
    for msg in &request.history {
        messages.push(serde_json::json!({
            "role": msg.role,
            "content": msg.content
        }));
    }

    // Current user message
    messages.push(serde_json::json!({
        "role": "user",
        "content": request.message
    }));

    let mut payload = serde_json::json!({
        "conversation_id": request.conversation_id,
        "messages": messages,
        "stream": true,
    });

    if let Some(ref model) = request.model {
        payload["model"] = serde_json::json!(model);
    }
    if let Some(temp) = request.temperature {
        payload["temperature"] = serde_json::json!(temp);
    }
    if let Some(max) = request.max_tokens {
        payload["max_tokens"] = serde_json::json!(max);
    }

    payload
}

// ---------------------------------------------------------------------------
// Tauri Commands
// ---------------------------------------------------------------------------

/// Stream a chat completion from the local LLM.
///
/// The command:
/// 1. Sends the user message to the Python sidecar for pseudonymization.
/// 2. Forwards the pseudonymized prompt to the local LLM (Ollama / llama.cpp).
/// 3. Streams response chunks back to the frontend via Tauri events (`ia:chat-stream`).
/// 4. De-pseudonymizes the final response before the last chunk.
///
/// # Events emitted
/// - `ia:chat-stream` — `ChatStreamChunk` for each token / group of tokens.
/// - `ia:chat-error`  — `{ conversationId, error }` on failure.
#[command]
pub async fn ia_chat_stream<R: Runtime>(
    app: AppHandle<R>,
    request: ChatRequest,
) -> Result<(), String> {
    // Validate sigilo level
    if request.sigilo_level > 5 {
        return Err("Nível de sigilo inválido (deve ser 1-5)".into());
    }

    let conversation_id = request.conversation_id.clone();

    // Spawn the streaming task so the command returns immediately.
    let app_handle = app.clone();
    tokio::spawn(async move {
        if let Err(e) = run_chat_stream(&app_handle, &request).await {
            let _ = app_handle.emit(
                "ia:chat-error",
                serde_json::json!({
                    "conversationId": conversation_id,
                    "error": e.to_string()
                }),
            );
        }
    });

    Ok(())
}

/// Internal implementation of the streaming chat pipeline.
async fn run_chat_stream<R: Runtime>(
    app: &AppHandle<R>,
    request: &ChatRequest,
) -> Result<(), AppError> {
    let sidecar = app
        .try_state::<Arc<Mutex<SidecarManager>>>()
        .ok_or_else(|| AppError::Internal("Sidecar manager not initialised".into()))?;

    let sidecar_guard = sidecar.lock().await;

    // -----------------------------------------------------------------------
    // Step 1: Pseudonymize the user message via the Python sidecar
    // -----------------------------------------------------------------------
    let pseudonymize_payload = serde_json::json!({
        "action": "pseudonymize",
        "text": request.message,
        "sigilo_level": request.sigilo_level,
    });

    let pseudo_response = sidecar_guard
        .call("pseudonymize", pseudonymize_payload)
        .await
        .map_err(|e| AppError::Sidecar(format!("Pseudonymization failed: {e}")))?;

    let pseudonymized_message = pseudo_response
        .get("text")
        .and_then(|v| v.as_str())
        .unwrap_or(&request.message)
        .to_string();

    // Build a modified request with the pseudonymized message
    let mut sanitized_request = request.clone();
    sanitized_request.message = pseudonymized_message;

    // Also pseudonymize history messages
    // TODO: Batch pseudonymization for history messages for better performance
    let mut sanitized_history = Vec::with_capacity(request.history.len());
    for msg in &request.history {
        if msg.role == "user" {
            let hist_payload = serde_json::json!({
                "action": "pseudonymize",
                "text": msg.content,
                "sigilo_level": request.sigilo_level,
            });
            let hist_response = sidecar_guard
                .call("pseudonymize", hist_payload)
                .await
                .map_err(|e| AppError::Sidecar(format!("History pseudonymization failed: {e}")))?;
            let sanitized_content = hist_response
                .get("text")
                .and_then(|v| v.as_str())
                .unwrap_or(&msg.content)
                .to_string();
            sanitized_history.push(ChatMessageDto {
                role: msg.role.clone(),
                content: sanitized_content,
            });
        } else {
            sanitized_history.push(msg.clone());
        }
    }
    sanitized_request.history = sanitized_history;

    // -----------------------------------------------------------------------
    // Step 2: Send to LLM via sidecar (streaming)
    // -----------------------------------------------------------------------
    let llm_payload = build_sidecar_payload(&sanitized_request);

    // The sidecar returns a stream of JSON lines (NDJSON).
    // Each line is a ChatStreamChunk-like object.
    let stream_receiver = sidecar_guard
        .call_stream("llm_chat", llm_payload)
        .await
        .map_err(|e| AppError::Sidecar(format!("LLM stream initiation failed: {e}")))?;

    // -----------------------------------------------------------------------
    // Step 3: Forward chunks to the frontend via Tauri events
    // -----------------------------------------------------------------------
    let mut full_response = String::new();
    let mut total_tokens: u32 = 0;

    while let Ok(chunk_json) = stream_receiver.recv_async().await {
        let delta = chunk_json
            .get("delta")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();

        let done = chunk_json
            .get("done")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);

        let token_count = chunk_json
            .get("token_count")
            .and_then(|v| v.as_u64())
            .map(|v| v as u32);

        if let Some(tc) = token_count {
            total_tokens = tc;
        }

        full_response.push_str(&delta);

        // If this is the final chunk, de-pseudonymize the full response
        let emit_delta = if done {
            // Step 4: De-pseudonymize the complete response
            let depseudo_payload = serde_json::json!({
                "action": "depseudonymize",
                "text": full_response,
                "sigilo_level": request.sigilo_level,
            });

            match sidecar_guard.call("depseudonymize", depseudo_payload).await {
                Ok(depseudo_response) => {
                    let depseudonymized = depseudo_response
                        .get("text")
                        .and_then(|v| v.as_str())
                        .unwrap_or(&full_response)
                        .to_string();
                    // For the final chunk, send the full de-pseudonymized text
                    // The frontend should replace the accumulated text with this
                    depseudonymized
                }
                Err(e) => {
                    // Log the error but still send the pseudonymized response
                    tracing::warn!(
                        conversation_id = %request.conversation_id,
                        error = %e,
                        "De-pseudonymization failed, returning pseudonymized response"
                    );
                    full_response.clone()
                }
            }
        } else {
            delta
        };

        let chunk = ChatStreamChunk {
            conversation_id: request.conversation_id.clone(),
            delta: emit_delta,
            done,
            token_count,
        };

        app.emit("ia:chat-stream", &chunk)
            .map_err(|e| AppError::Internal(format!("Failed to emit chat chunk: {e}")))?;

        if done {
            break;
        }
    }

    // -----------------------------------------------------------------------
    // Step 5: Audit log
    // -----------------------------------------------------------------------
    // TODO: Write audit entry to SQLCipher via infra::database
    // Should record: conversation_id, timestamp, user_id, token_count,
    // model used, sigilo_level. Must NOT store message content for sigilo >= 3.
    tracing::info!(
        conversation_id = %request.conversation_id,
        tokens = total_tokens,
        sigilo = request.sigilo_level,
        "Chat completion finished"
    );

    Ok(())
}

/// Cancel an in-progress chat stream.
#[command]
pub async fn ia_chat_cancel<R: Runtime>(
    app: AppHandle<R>,
    conversation_id: String,
) -> Result<(), String> {
    let sidecar = app
        .try_state::<Arc<Mutex<SidecarManager>>>()
        .ok_or("Sidecar manager not initialised")?;

    let sidecar_guard = sidecar.lock().await;

    sidecar_guard
        .call(
            "llm_cancel",
            serde_json::json!({ "conversation_id": conversation_id }),
        )
        .await
        .map_err(|e| format!("Failed to cancel stream: {e}"))?;

    // Emit a final "done" chunk so the frontend cleans up.
    let chunk = ChatStreamChunk {
        conversation_id,
        delta: String::new(),
        done: true,
        token_count: None,
    };
    app.emit("ia:chat-stream", &chunk)
        .map_err(|e| format!("Failed to emit cancel chunk: {e}"))?;

    Ok(())
}

/// Check the availability and status of the local AI backend.
#[command]
pub async fn ia_status<R: Runtime>(
    app: AppHandle<R>,
) -> Result<AiStatusResponse, String> {
    let sidecar = app
        .try_state::<Arc<Mutex<SidecarManager>>>()
        .ok_or("Sidecar manager not initialised")?;

    let sidecar_guard = sidecar.lock().await;

    let response = sidecar_guard
        .call("llm_status", serde_json::json!({}))
        .await
        .map_err(|e| format!("Failed to query AI status: {e}"))?;

    let available = response
        .get("available")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);

    let backend = response
        .get("backend")
        .and_then(|v| v.as_str())
        .unwrap_or("none")
        .to_string();

    let models = response
        .get("models")
        .and_then(|v| v.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    Ok(AiStatusResponse {
        available,
        backend,
        models,
    })
}

/// List available local LLM models.
#[command]
pub async fn ia_list_models<R: Runtime>(
    app: AppHandle<R>,
) -> Result<Vec<String>, String> {
    let status = ia_status(app).await?;
    Ok(status.models)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_build_sidecar_payload_defaults() {
        let request = ChatRequest {
            conversation_id: "test-123".into(),
            message: "Qual o prazo para recurso?".into(),
            history: vec![],
            sigilo_level: 1,
            model: None,
            system_prompt: None,
            temperature: None,
            max_tokens: None,
        };

        let payload = build_sidecar_payload(&request);

        let messages = payload["messages"].as_array().unwrap();
        assert_eq!(messages.len(), 2); // system + user
        assert_eq!(messages[0]["role"], "system");
        assert_eq!(messages[1]["role"], "user");
        assert_eq!(messages[1]["content"], "Qual o prazo para recurso?");
        assert_eq!(payload["stream"], true);
        assert!(payload.get("model").is_none());
    }

    #[test]
    fn test_build_sidecar_payload_with_overrides() {
        let request = ChatRequest {
            conversation_id: "test-456".into(),
            message: "Analise este contrato.".into(),
            history: vec![
                ChatMessageDto {
                    role: "user".into(),
                    content: "Olá".into(),
                },
                ChatMessageDto {
                    role: "assistant".into(),
                    content: "Olá! Como posso ajudar?".into(),
                },
            ],
            sigilo_level: 3,
            model: Some("llama3".into()),
            system_prompt: Some("Você é um especialista em contratos.".into()),
            temperature: Some(0.3),
            max_tokens: Some(2048),
        };

        let payload = build_sidecar_payload(&request);

        let messages = payload["messages"].as_array().unwrap();
        // system + 2 history + current user = 4
        assert_eq!(messages.len(), 4);
        assert_eq!(messages[0]["content"], "Você é um especialista em contratos.");
        assert_eq!(payload["model"], "llama3");
        assert_eq!(payload["temperature"], 0.3);
        assert_eq!(payload["max_tokens"], 2048);
    }

    #[test]
    fn test_chat_stream_chunk_serialization() {
        let chunk = ChatStreamChunk {
            conversation_id: "conv-1".into(),
            delta: "Olá".into(),
            done: false,
            token_count: Some(5),
        };

        let json = serde_json::to_value(&chunk).unwrap();
        assert_eq!(json["conversationId"], "conv-1");
        assert_eq!(json["delta"], "Olá");
        assert_eq!(json["done"], false);
        assert_eq!(json["tokenCount"], 5);
    }
}
